workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: linux
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "org.test.guesstheflag"
    scripts:
      - name: Pull Kivy Docker image
        script: |
          docker pull kivy/buildozer
          
      - name: Build APK in Docker
        script: |
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer bash -c "cd /home/user/hostcwd && buildozer android debug"
          
    artifacts:
      - bin/*.apk
