workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "org.test.guesstheflag"
    scripts:
      - name: Install dependencies
        script: |
          brew install python@3.10
          python3 -m pip install --upgrade pip
          pip3 install buildozer==1.5.0
          pip3 install cython==0.29.33
          
      - name: Install system dependencies
        script: |
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer
          
      - name: Build APK
        script: |
          buildozer init
          buildozer android debug
          
    artifacts:
      - build/**/*.apk
